- .gitmodules
git:// gives trouble on Enterprise™ networks :(
> git:// to https://

- misc_jazzy_features/after/docs/Classes.html
- misc_jazzy_features/after/docs/Classes/ClassWithInitializers.html
- misc_jazzy_features/after/docs/Classes/ImplicitlyInternalTopLevelClass.html
- misc_jazzy_features/after/docs/Enums.html
- misc_jazzy_features/after/docs/Enums/DocumentedEnum.html
- misc_jazzy_features/after/docs/Enums/UndocumentedEnum.html
- misc_jazzy_features/after/docs/Global Variables.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Classes.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Classes/ClassWithInitializers.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Classes/ImplicitlyInternalTopLevelClass.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Enums.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Enums/DocumentedEnum.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Enums/UndocumentedEnum.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Global Variables.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/index.html
- misc_jazzy_features/after/docs/index.html
- misc_jazzy_features/after/execution_output.txt
Dependency for https://github.com/realm/jazzy/pull/308
> Hidden coverage

- document_moya_podspec/after/execution_output.txt
- misc_jazzy_features/after/docs/Classes/ClassWithInitializers.html
- misc_jazzy_features/after/docs/Other Enums.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Classes/ClassWithInitializers.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Other Enums.html
- misc_jazzy_features/before/Sections/ClassWithInitializers.md
This is related to a PR I'm about to open for issue [600](https://github.com/realm/jazzy/issues/600)
> Update specs for abstract command fix

- document_alamofire/after/docs/css/jazzy.css
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/css/jazzy.css
- document_moya_podspec/after/docs/css/jazzy.css
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_objc/after/docs/css/jazzy.css
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_swift/after/docs/css/jazzy.css
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/css/jazzy.css
Specs update for realm/jazzy#770
> Update for jazzy link-valign branch

- document_siesta/after/execution_output.txt
- misc_jazzy_features/after/docs/Extensions/String.html
- misc_jazzy_features/after/docs/Extensions/String/CharacterView.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Extensions/String.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Extensions/String/CharacterView.html
jazzy is already pointing to this
> update for jf-xcode-91

- document_alamofire/after/docs/css/jazzy.css
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/css/jazzy.css
- document_moya_podspec/after/docs/css/jazzy.css
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_objc/after/docs/css/jazzy.css
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_swift/after/docs/css/jazzy.css
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/css/jazzy.css
- document_siesta/after/api-docs/css/jazzy.css
- document_siesta/after/api-docs/docsets/Siesta.docset/Contents/Resources/Documents/css/jazzy.css
- misc_jazzy_features/after/docs/Guides.html
- misc_jazzy_features/after/docs/css/jazzy.css
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Guides.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/css/jazzy.css
- misc_jazzy_objc_features/after/docs/css/jazzy.css
- misc_jazzy_objc_features/after/docs/docsets/JazzyKit.docset/Contents/Resources/Documents/css/jazzy.css
Spec updates for realm/jazzy#985.
> updates for jf-guide-index2

- document_alamofire/after/docs/css/jazzy.css
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/css/jazzy.css
- document_moya_podspec/after/docs/css/jazzy.css
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_objc/after/docs/css/jazzy.css
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_swift/after/docs/css/jazzy.css
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/css/jazzy.css
> updates for jf-multiline-copyright2

- document_moya_podspec/after/execution_output.txt
> updates for jf-release-096

- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/js/jazzy.js
- document_alamofire/after/docs/js/jazzy.js
- document_moya_podspec/after/docs/css/jazzy.css
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/css/jazzy.css
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/js/jazzy.js
- document_moya_podspec/after/docs/js/jazzy.js
- document_realm_objc/after/docs/css/jazzy.css
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/js/jazzy.js
- document_realm_objc/after/docs/js/jazzy.js
- document_realm_swift/after/docs/css/jazzy.css
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/js/jazzy.js
- document_realm_swift/after/docs/js/jazzy.js
- document_siesta/after/api-docs/docsets/Siesta.docset/Contents/Resources/Documents/js/jazzy.js
- document_siesta/after/api-docs/js/jazzy.js
- misc_jazzy_features/after/docs/css/jazzy.css
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/css/jazzy.css
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/js/jazzy.js
- misc_jazzy_features/after/docs/js/jazzy.js
- misc_jazzy_objc_features/after/docs/docsets/JazzyKit.docset/Contents/Resources/Documents/js/jazzy.js
- misc_jazzy_objc_features/after/docs/js/jazzy.js
> updates for jf-js-sections

- document_alamofire/after/docs/css/jazzy.css
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/css/jazzy.css
- document_moya_podspec/after/docs/css/jazzy.css
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_objc/after/docs/css/jazzy.css
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_swift/after/docs/css/jazzy.css
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/css/jazzy.css
- document_siesta/after/api-docs/css/jazzy.css
- document_siesta/after/api-docs/docsets/Siesta.docset/Contents/Resources/Documents/css/jazzy.css
- misc_jazzy_features/after/docs/css/jazzy.css
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/css/jazzy.css
- misc_jazzy_objc_features/after/docs/css/jazzy.css
- misc_jazzy_objc_features/after/docs/docsets/JazzyKit.docset/Contents/Resources/Documents/css/jazzy.css
> updates for jf-csass

- document_moya_podspec/after/execution_output.txt
> updates for jf-stable-ci

- misc_jazzy_features/after/docs/Extensions/String.html
- misc_jazzy_features/after/docs/Extensions/String/CharacterView.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Extensions/String.html
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Extensions/String/CharacterView.html
> updates for jf-catalina

- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/js/jazzy.js
- document_alamofire/after/docs/js/jazzy.js
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/js/jazzy.js
- document_moya_podspec/after/docs/js/jazzy.js
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/js/jazzy.js
- document_realm_objc/after/docs/js/jazzy.js
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/js/jazzy.js
- document_realm_swift/after/docs/js/jazzy.js
- document_siesta/after/api-docs/docsets/Siesta.docset/Contents/Resources/Documents/js/jazzy.js
- document_siesta/after/api-docs/js/jazzy.js
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/js/jazzy.js
- misc_jazzy_features/after/docs/js/jazzy.js
- misc_jazzy_objc_features/after/docs/docsets/JazzyKit.docset/Contents/Resources/Documents/js/jazzy.js
- misc_jazzy_objc_features/after/docs/js/jazzy.js
> Apple ref anchors expand docs

- document_siesta/after/api-docs/Protocols/Request.html
- document_siesta/after/api-docs/docsets/Siesta.docset/Contents/Resources/Documents/Protocols/Request.html
> Updates for jazzy-jf-release-0-13-2

- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Info.plist
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Info.plist
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Info.plist
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Info.plist
- misc_jazzy_features/before/.jazzy.yaml
> updates for jf-docset-options

- document_alamofire/after/docs/css/jazzy.css
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/css/jazzy.css
- document_siesta/after/api-docs/css/jazzy.css
- document_siesta/after/api-docs/docsets/Siesta.docset/Contents/Resources/Documents/css/jazzy.css
- misc_jazzy_objc_features/after/docs/css/jazzy.css
- misc_jazzy_objc_features/after/docs/docsets/JazzyKit.docset/Contents/Resources/Documents/css/jazzy.css
> updates for jf-release-0-13-3

- document_moya_podspec/after/docs/css/jazzy.css
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_objc/after/docs/css/jazzy.css
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/css/jazzy.css
- document_realm_swift/after/docs/css/jazzy.css
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/css/jazzy.css
- misc_jazzy_features/after/docs/css/jazzy.css
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/css/jazzy.css
> updates for jf-css-tweaks

- document_alamofire/after/docs/Classes.html
- document_alamofire/after/docs/Classes/SessionDelegate.html
- document_alamofire/after/docs/Classes/SessionManager.html
- document_alamofire/after/docs/Functions.html
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/Classes.html
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/Classes/SessionDelegate.html
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/Classes/SessionManager.html
- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/Functions.html
- document_realm_objc/after/docs/Categories/NSError(RLMSync).html
- document_realm_objc/after/docs/Classes/RLMRealm.html
- document_realm_objc/after/docs/Classes/RLMSyncManager.html
- document_realm_objc/after/docs/Classes/RLMSyncSession.html
- document_realm_objc/after/docs/Classes/RLMSyncUser.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Categories/NSError(RLMSync).html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMRealm.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMSyncManager.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMSyncSession.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMSyncUser.html
- document_siesta/after/execution_output.txt
- misc_jazzy_objc_features/before/MiscJazzyObjcFeatures.xcodeproj/project.pbxproj
> updates for jf-xcode-12

- misc_jazzy_symgraph_features/after/docs/Functions/functionA_28_5F_3AbParameter_3A_29_5F.html
- misc_jazzy_symgraph_features/after/docs/Functions/functionB_28_5F_3A_29_5F.html
- misc_jazzy_symgraph_features/after/docs/Functions/functionC_28_5F_3A_29_5F.html
- misc_jazzy_symgraph_features/after/docs/Functions/functionE_28_5F_3A_29_5F.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Functions/functionA_28_5F_3AbParameter_3A_29_5F.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Functions/functionB_28_5F_3A_29_5F.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Functions/functionC_28_5F_3A_29_5F.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Functions/functionE_28_5F_3A_29_5F.html
> updates for jf-symgraph-params

- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/index.html
- misc_jazzy_features/after/docs/index.html
- misc_jazzy_features/before/README.md
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/index.html
- misc_jazzy_symgraph_features/after/docs/index.html
> updates for jf-bad-space

- misc_jazzy_symgraph_features/after/execution_output.txt
> Fix symbolgraph mode on Xcode 13

- misc_jazzy_symgraph_features/after/docs/Enums/DocumentedEnum.html
- misc_jazzy_symgraph_features/after/docs/Enums/StringEnum.html
- misc_jazzy_symgraph_features/after/docs/Enums/UndocumentedEnum.html
- misc_jazzy_symgraph_features/after/docs/Structs/Nop.html
- misc_jazzy_symgraph_features/after/docs/Structs/PropertyWrapperClient.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Enums/DocumentedEnum.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Enums/StringEnum.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Enums/UndocumentedEnum.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Structs/Nop.html
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/Structs/PropertyWrapperClient.html
> updates for jf-xcode132

- document_alamofire/after/execution_output.txt
- document_moya_podspec/after/execution_output.txt
- document_realm_swift/after/execution_output.txt
- document_siesta/after/execution_output.txt
- misc_jazzy_features/after/execution_output.txt
- misc_jazzy_symgraph_features/after/execution_output.txt
> updates for jf-package-vis

- document_realm_objc/after/docs/Classes/RLMAppConfiguration.html
- document_realm_objc/after/docs/Classes/RLMCredentials.html
- document_realm_objc/after/docs/Classes/RLMSyncConfiguration.html
- document_realm_objc/after/docs/Classes/RLMUser.html
- document_realm_objc/after/docs/Functions.html
- document_realm_objc/after/docs/Protocols/RLMChangeEventDelegate.html
- document_realm_objc/after/docs/Type Definitions.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMAppConfiguration.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMCredentials.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMSyncConfiguration.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Classes/RLMUser.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Functions.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Protocols/RLMChangeEventDelegate.html
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/Type Definitions.html
- misc_jazzy_symgraph_features/after/execution_output.txt
> updates for jf-xcode15rc

- document_alamofire/after/docs/docsets/Alamofire.docset/Contents/Resources/Documents/js/jazzy.js
- document_alamofire/after/docs/js/jazzy.js
- document_moya_podspec/after/docs/docsets/Moya.docset/Contents/Resources/Documents/js/jazzy.js
- document_moya_podspec/after/docs/js/jazzy.js
- document_realm_objc/after/docs/docsets/Realm.docset/Contents/Resources/Documents/js/jazzy.js
- document_realm_objc/after/docs/js/jazzy.js
- document_realm_swift/after/docs/docsets/RealmSwift.docset/Contents/Resources/Documents/js/jazzy.js
- document_realm_swift/after/docs/js/jazzy.js
- document_siesta/after/api-docs/docsets/Siesta.docset/Contents/Resources/Documents/js/jazzy.js
- document_siesta/after/api-docs/js/jazzy.js
- jazzy_multi_modules/after/docs/docsets/Jazzy_MultiKit.docset/Contents/Resources/Documents/js/jazzy.js
- jazzy_multi_modules/after/docs/js/jazzy.js
- misc_jazzy_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/js/jazzy.js
- misc_jazzy_features/after/docs/js/jazzy.js
- misc_jazzy_objc_features/after/docs/docsets/JazzyKit.docset/Contents/Resources/Documents/js/jazzy.js
- misc_jazzy_objc_features/after/docs/js/jazzy.js
- misc_jazzy_symgraph_features/after/docs/docsets/MiscJazzyFeatures.docset/Contents/Resources/Documents/js/jazzy.js
- misc_jazzy_symgraph_features/after/docs/js/jazzy.js
> updates for typo fix
